# Generated by Django 4.2.11 on 2024-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Общепит', 'Общепит'), ('Ритейл', 'Ритейл'), ('Услуги по записи', 'Услуги по записи')])),
            ],
        ),
    ]
