# Generated by Django 4.2.11 on 2024-05-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
