# Generated by Django 4.2.11 on 2024-05-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_delete_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('type_business', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=155)),
                ('answers', models.JSONField()),
            ],
        ),
    ]
